language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install -r requirements.txt
script:
    - py.test
branches:
  only:
   - master
notifications:
  email:
    recipients:
      - khelil.sator@gmail.com
    on_success: always
    on_failure: always
