language: python
# python versions to use during the tests
python:
    - "2.7"
    - "3.4"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - py.test
branches:
  only:
   - master
notifications:
  email:
    recipients:
      - khelil.sator@gmail.com
    on_success: always
    on_failure: always
after_success:
    - coveralls
